name: project
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.12.0
  image_picker: ^1.2.1
  path: ^1.9.1
  file_picker: ^10.3.8
  just_audio: ^0.10.5
  uuid: ^4.5.2
  audioplayers: ^6.5.1
  shimmer: ^3.0.0
  simple_animations: ^5.2.0
  http: ^1.6.0
  intl: ^0.20.2
  otp: ^3.0.1
  qr_flutter: ^4.1.0
  shared_preferences: ^2.2.2
  encrypt: ^5.0.3
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0


flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/spotify.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/icon/spotify.png